# -*- coding: utf-8 -*-
"""Copy of main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lY4AY4iM1oJBv6qbkaWQPdji1fTBVV34
"""

import streamlit as st
st.title("My first streamlit app")
st.write("Hello! Creating a simple web application using streamlit")
st.text_input("Enter your name")
if st.button("submit"):
st.write(f"hello, (name): welcome to streamlit")
